// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRXH4uAanmZtDUhTbWUMMyslqYgojmeAA',
    appId: '1:75911745216:web:971ae94e83bdf9eb35e725',
    messagingSenderId: '75911745216',
    projectId: 'donnation-542a8',
    authDomain: 'donnation-542a8.firebaseapp.com',
    storageBucket: 'donnation-542a8.firebasestorage.app',
    measurementId: 'G-VPJ9VH8DR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAKQMhDbxBaaXS9CvdS0Lzfe7kyuOd5E',
    appId: '1:75911745216:android:c0b229b81b3bcff835e725',
    messagingSenderId: '75911745216',
    projectId: 'donnation-542a8',
    storageBucket: 'donnation-542a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKa6l0WcS5RtUMNgrH6MtUkJY3fW8Urpg',
    appId: '1:75911745216:ios:b81fa8e4778f67e435e725',
    messagingSenderId: '75911745216',
    projectId: 'donnation-542a8',
    storageBucket: 'donnation-542a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKa6l0WcS5RtUMNgrH6MtUkJY3fW8Urpg',
    appId: '1:75911745216:ios:b81fa8e4778f67e435e725',
    messagingSenderId: '75911745216',
    projectId: 'donnation-542a8',
    storageBucket: 'donnation-542a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRXH4uAanmZtDUhTbWUMMyslqYgojmeAA',
    appId: '1:75911745216:web:e5d20aab722479a935e725',
    messagingSenderId: '75911745216',
    projectId: 'donnation-542a8',
    authDomain: 'donnation-542a8.firebaseapp.com',
    storageBucket: 'donnation-542a8.firebasestorage.app',
    measurementId: 'G-6SM89W7W1K',
  );
}
